apiVersion: apps/v1
kind: Deployment
metadata:
  name: barman-api
spec:
  selector:
    matchLabels:
      app: barman-api
  template:
    metadata:
      labels:
        app: barman-api
    spec:
      containers:
      - image: barman-api:001
        name: barman-api
        imagePullPolicy: Never
        env:
        - name: DATABASE_URL
          value: "postgresql://kd:pass@barman-db-svc:5432/data?schema=public"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: barman-api-svc
spec:
  selector:
    app: barman-api
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
