name: build-and-push

on:
  push:
    branches:
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Current date time
        id: date
        # You may pin to the exact commit or the version.
        # uses: kaven-universe/github-action-current-date-time@f2c12d90cff9c3e7b1f50430886e632fe31fcee1
        uses: kaven-universe/github-action-current-date-time@v1.4.0
        with:
          format: "YYYY_MM_DD_HH_mm_ss"
          
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: kermodebear000/barman-api:${{github.run_number }}
